export default recipeData = {
    "brandyalexander": {
        "name": "Brandy Alexander",
        "shortDescription": "A rich, creamy classic",
        "imgUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Brandy_alexander.jpg/500px-Brandy_alexander.jpg",
        "description": "A Brandy Alexander is a brandy-based dessert cocktail consisting of cognac, crème de cacao, and cream, that became popular during the early 20th century.",
        "garnishes": "Garnish with grated nutmeg",
        "instructions": "Shake and strain into a chilled cocktail glass. Sprinkle with fresh ground nutmeg.",
        "ingredients": [
            {
                "number": 1,
                "name": "cognac",
                "quantity": 45,
                "quantityUnit": "ml",
            },
            {
                "number": 2,
                "name": "crème de cacao",
                "quantity": 30,
                "quantityUnit": "ml",
            },
            {
                "number": 3,
                "name": "cream",
                "quantity": 25,
                "quantityUnit": "ml",
            },
        ],
    },
    "applejack": {
        "name": "Apple Jack",
        "shortDescription": "Based on apple brandy",
        "imgUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b3/Jack_Rose_Cocktail.jpg/500px-Jack_Rose_Cocktail.jpg",
        "description": "Sweet and sour with rich apple flavours and a brandy backbone.",
        "garnishes": null,
        "instructions": "Shake all ingredients with ice and strain into a chilled cocktail glass.",
        "ingredients": [
            {
                "number": 1,
                "name": "applejack brandy",
                "quantity": 45,
                "quantityUnit": "ml",
            },
            {
                "number": 2,
                "name": "apple juice",
                "quantity": 15,
                "quantityUnit": "ml",
            },
            {
                "number": 3,
                "name": "lemon juice",
                "quantity": 15,
                "quantityUnit": "ml",
            },
            {
                "number": 4,
                "name": "simple syrup",
                "quantity": 7.5,
                "quantityUnit": "ml",
            },
        ],
    },
    "oldfashioned": {
        "name": "Old Fashioned",
        "shortDescription": "Traditional whiskey cocktail with bitters",
        "imgUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Whiskey_Old_Fashioned1.jpg/500px-Whiskey_Old_Fashioned1.jpg",
        "description": "The old fashioned is a cocktail made by muddling sugar with bitters and water, adding whiskey (typically rye or bourbon), and garnishing with an orange slice or zest and a cocktail cherry. It is traditionally served with ice in an old fashioned glass (also known as a rocks glass).\n\n[[par]]Developed during the 19th century and given its name in the 1880s, it is an IBA Official Cocktail. It is also one of six basic drinks listed in David A. Embury's The Fine Art of Mixing Drinks.",
        "garnishes": "Orange zest twist",
        "instructions": "Stir all ingredients with ice and strain into an ice filled tumbler.",
        "ingredients": [
            {
                "number": 1,
                "name": "sugar cube",
                "quantity": 1,
                "quantityUnit": "unit",
            },
            {
                "number": 2,
                "name": "bourbon whiskey",
                "quantity": 45,
                "quantityUnit": "ml",
            },
            {
                "number": 3,
                "name": "Angostura bitters",
                "quantity": null,
                "quantityUnit": "dash",
            },
            {
                "number": 4,
                "name": "water",
                "quantity": null,
                "quantityUnit": "dash",
            },
        ],
    },
    "americano": {
        "name": "Americano",
        "shortDescription": "Sparkling drink of Campari and sweet vermouth",
        "imgUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Americano_cocktail_at_Nightwood_Restaurant.jpg/500px-Americano_cocktail_at_Nightwood_Restaurant.jpg",
        "description": "Made with Campari, sweet vermouth, and garnished with a slice of lemon.",
        "garnishes": "Garnish with a slice of lemon",
        "instructions": null,
        "ingredients": [
            {
                "number": 1,
                "name": "Campari",
                "quantity": 45,
                "quantityUnit": "ml",
            },
            {
                "number": 2,
                "name": "sweet vermouth",
                "quantity": 45,
                "quantityUnit": "ml",
            },
            {
                "number": 3,
                "name": "soda water",
                "quantity": 75,
                "quantityUnit": "ml",
            },
        ],
    },
    "[template]": {
        "name": "[string]",
        "shortDescription": "[string]",
        "imgUrl": "[url]",
        "description": "[string]",
        "garnishes": "[string]",
        "instructions": "[string]",
        "ingredients": [
            {
                "number": 1,
                "name": "name",
                "quantity": 1,
                "quantityUnit": "unit",
            },
        ],
    },
};